"""Add additional_metadata to sales table

Revision ID: a12103505d4f
Revises: 
Create Date: 2026-01-16 06:24:22.310969+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a12103505d4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_inventory_items_supplier_id', 'suppliers', ['supplier_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('location_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('extra_metadata')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_metadata', sqlite.JSON(), nullable=True))
        batch_op.alter_column('location_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('additional_metadata')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_items_supplier_id', type_='foreignkey')

    # ### end Alembic commands ###
